---
- name: Install CoGe
  hosts: all
  become: yes
  become_method: sudo
  vars_files:
    - coge_vars_local.yml

  roles:
    - { role: coge.packages }
    - { role: coge.mysql }
    - { role: coge.src }
    - { role: coge.apache }

  tasks:
    - name: install htop
      package:
        name: htop
        state: latest
